# Generated by Django 3.2.12 on 2022-11-16 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_image', models.ImageField(upload_to='media')),
                ('teacher_name', models.CharField(max_length=50)),
                ('teacher_details', models.TextField()),
                ('course_description', models.TextField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
