# Generated by Django 3.2.12 on 2022-11-16 11:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 11, 2, 53, 711141, tzinfo=utc)),
        ),
    ]
