# Generated by Django 3.2.12 on 2022-11-16 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_assignment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 11, 29, 29, 786955, tzinfo=utc)),
        ),
    ]
