# Generated by Django 3.2.8 on 2022-11-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20221121_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='code',
            field=models.CharField(default='00000', max_length=100),
        ),
    ]
