# Generated by Django 3.2.8 on 2022-11-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_assignmentsubmission_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='Title',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='no',
            field=models.IntegerField(default=0),
        ),
    ]
