# Generated by Django 3.2.8 on 2022-11-22 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.decorators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20221122_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(null=True, upload_to='file/', validators=[users.decorators.validate_file], verbose_name=''),
        ),
        migrations.CreateModel(
            name='GradeAssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=0)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('NO', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
