# Generated by Django 3.2.8 on 2022-11-24 14:37

from django.db import migrations, models
import users.decorators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20221122_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='extensions',
            field=models.TextField(default='00000'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='related_file',
            field=models.FileField(blank=True, null=True, upload_to='file1/', validators=[users.decorators.validate_file]),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(null=True, upload_to='<django.db.models.fields.TextField>/', validators=[users.decorators.validate_file], verbose_name=''),
        ),
    ]
