# Generated by Django 3.2.8 on 2022-11-24 18:51

from django.db import migrations, models
import users.decorators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20221124_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file_directory_structure_textfile',
            field=models.FileField(blank=True, null=True, upload_to='file1/', validators=[users.decorators.validate_file]),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='related_file',
            field=models.FileField(blank=True, null=True, upload_to='file1/'),
        ),
    ]
