# Generated by Django 3.2.8 on 2022-11-24 21:55

from django.db import migrations, models
import users.decorators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20221124_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='', upload_to=' ')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='assignment',
            name='file_directory_structure_textfile',
            field=models.FileField(blank=True, null=True, upload_to='file1/', validators=[users.decorators.valid]),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(null=True, upload_to='file/'),
        ),
    ]
