# Generated by Django 3.2.8 on 2022-11-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20221125_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='autograde_script',
            field=models.FileField(blank=True, null=True, upload_to='file1/'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='format',
            field=models.BooleanField(default=True),
        ),
    ]
