# Generated by Django 3.2.8 on 2022-11-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20221125_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='autograde_script_name',
            field=models.CharField(default='00000', max_length=100),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='grade',
            field=models.FloatField(default=-1),
        ),
    ]
