# Generated by Django 3.2.12 on 2022-11-25 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20221125_0748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='autograde_script',
            new_name='autograde_script_zipfile',
        ),
    ]
