# Generated by Django 3.2.12 on 2022-11-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_rename_autograde_script_assignment_autograde_script_zipfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_marks',
            field=models.IntegerField(max_length=20),
        ),
    ]
