# Generated by Django 3.2.8 on 2022-11-25 13:20

from django.db import migrations, models
import users.decorators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_assignment_assignment_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='autograde_script_zipfile',
            field=models.FileField(blank=True, null=True, upload_to='file1/', validators=[users.decorators.valid1]),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='feedback',
            field=models.TextField(blank=True, default='THIS IS MANUALLY GRADED', null=True),
        ),
    ]
